title: Code In Place 2025 AI Evaluation Project
description: Towards Scalable Coding Support in a Massive Global Course
show_downloads: true
google_analytics:
theme: jekyll-theme-cayman
remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
