name: "sft_v1"
args:
  learning_rate: 0.00001
  num_train_epochs: 5
  lr_scheduler_type: cosine
  completion_only_loss: True
  warmup_ratio: 0.1

lora:
  r: 64
  lora_alpha: 128
  use_rslora: True
  target_modules: "all-linear"

sampling:
  train_frac: 0.9
  head_frac: 0.50
